"""
Django settings for hospitalapp project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=pt$(j6v5llxh@wql=$f@pb0#6lqi!lq2f((bo!^p$os*k=o4)'

# SECURITY WARNING: don't run with debug turned on in production! True, False
DEBUG = True

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INDRANIL_WORK = ['v1.patientapi.apps.PatientapiConfig',]


INSTALLED_APPS = [
    'user.apps.UserConfig',

    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'knox',
    'hospital',
    'website',
    'apimaster',
    'verification',
    'clear_cache',
    #'django.contrib.gis',
]+INDRANIL_WORK

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'hospitalapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospitalapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {







    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    
    # 'default': {
    #     'ENGINE': 'djongo',
    #     'NAME': 'hospitaldjangodb',
    #     'ENFORCE_SCHEMA': False,
    #     'CLIENT': {
    #         'host': 'mongodb+srv://brtechgeeks:CCzzgyxxdc88@cluster0.huvf6.mongodb.net/test'
    #     }  
    # }

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hospital',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }

    #'host': 'pymongo.MongoClient("mongodb://brtechgeeks:CCzzgyxxdc88@cluster0-shard-00-00.huvf6.mongodb.net:27017,cluster0-shard-00-01.huvf6.mongodb.net:27017,cluster0-shard-00-02.huvf6.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-uzef1q-shard-0&authSource=admin&retryWrites=true&w=majority")'
    #'host': 'mongodb+srv://brtechgeeks:CCzzgyxxdc88@cluster0.huvf6.mongodb.net/test'
    #'host': 'mongodb+srv://<username>:<password>@<atlas cluster>/<myFirstDatabase>?retryWrites=true&w=majority'
}


# DATABASES['default'] = {

# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication', # For Token Verification
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
        
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.AllowAny',
    #     #'rest_framework.permissions.IsAdminUser',
    #     #'rest_framework.permissions.IsAuthenticated',
    # ]
}

#AUTH_USER_MODEL='UserManagement.Users'

CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',
    'http://localhost:8004',
)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

DATETIME_FORMAT="%Y-%m-%d %H:%M:%S"
TIME_ZONE =  'Asia/Calcutta'
#TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'

PHONENUMBER_DB_FORMAT = 'E164'
PHONENUMBER_DEFAULT_REGION = "IN"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'hospital'
LOGOUT_REDIRECT_URL = 'login'
#LOGIN_REDIRECT_URL = 'http://127.0.0.1:8004/hospital/'

################################ MEDIA ####################################################
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_URL = '/static/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

# ROOT_DIR = os.path.dirname(os.path.dirname(__file__))
# def location(f):
#     return os.path.join(ROOT_DIR, f)
# MEDIA_URL = 'http://127.0.0.1:8004/media/'
# MEDIA_ROOT = location('media/')
###########################################################################################

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    #'/var/www/static/',
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#LOGIN_REDIRECT_URL = 'dashboard'
# This will print email in Console.
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 

#from django.contrib.messages import constants as messages
from django.contrib import messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
} 

# email settings
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'demo.developer21@gmail.com'
# EMAIL_HOST_PASSWORD = 'admin@1234'
# DEFAULT_FROM_EMAIL = '<anything you want>'

# end 
