# Generated by Django 3.2.8 on 2021-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
