# Generated by Django 3.2.9 on 2021-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0012_auto_20211212_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersregistrationcouncils',
            name='profile',
        ),
        migrations.AddField(
            model_name='usersregistrationcouncils',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
