# Generated by Django 3.2.9 on 2021-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0014_alter_userprofiles_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='language_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='specialty_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='establishmenttimings',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='establishmenttimings',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
