# Generated by Django 3.2.9 on 2022-01-03 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0016_alter_userprofiles_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVerifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Issues text', max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('issues_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'UsersIssues',
            },
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
