# Generated by Django 3.2.9 on 2022-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0017_auto_20220103_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='verification_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
