# Generated by Django 3.2.9 on 2022-01-04 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0019_modellanguages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersWorkExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='org name text', max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dol', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='doctors_docs/', verbose_name='file')),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'UsersWorkExperiences',
            },
        ),
    ]
