# Generated by Django 3.2.9 on 2022-01-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0020_usersworkexperiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
