# Generated by Django 3.2.9 on 2022-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0021_alter_userprofiles_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='Section_flag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
