# Generated by Django 3.2.9 on 2022-01-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0022_userprofiles_section_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='Section_flag',
            new_name='section_flag',
        ),
    ]
