# Generated by Django 3.2.9 on 2022-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0025_alter_userprofiles_section_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='flag_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
