# Generated by Django 3.2.9 on 2022-01-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0026_userprofiles_flag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='verification',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
