# Generated by Django 3.2.9 on 2022-02-01 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20220124_1700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apimaster', '0028_auto_20220201_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='specialty',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.treatments'),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='apimaster.userprofiles'),
        ),
    ]
