# Generated by Django 3.2.9 on 2022-02-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0030_familymemberprofiles_feveratedoctors_recommendeddoctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemberprofiles',
            name='blood_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userseducations',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userseducations',
            name='from_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
