# Generated by Django 3.2.9 on 2022-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0031_auto_20220203_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='phone_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
