# Generated by Django 3.2.9 on 2022-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimaster', '0033_usersclinicimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersclinics',
            name='from_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersclinics',
            name='to_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
