# Generated by Django 3.2.9 on 2022-02-11 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apimaster', '0035_establishmenttimings_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmenttimings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='establishmenttimings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_time_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='establishmenttimings',
            name='name',
            field=models.CharField(blank=True, default='Name of days', max_length=50, null=True),
        ),
    ]
