# Generated by Django 3.2.8 on 2021-11-26 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20211125_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='heading text', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=150)),
                ('primary_image', models.CharField(blank=True, max_length=150)),
                ('sort_id', models.IntegerField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True)),
                ('updated_by', models.IntegerField(blank=True)),
                ('deleted_by', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='treatments',
            name='primary_image',
            field=models.FileField(blank=True, upload_to='Treatments/', verbose_name='primary_image'),
        ),
    ]
