# Generated by Django 3.2.8 on 2021-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20211126_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='primary_image',
            field=models.FileField(blank=True, upload_to='treatments/', verbose_name='primary_image'),
        ),
    ]
