# Generated by Django 3.2.9 on 2021-11-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20211130_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionhistory',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
