# Generated by Django 3.2.9 on 2021-12-02 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_rename_plan_id_subscriptionhistory_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='heading text', max_length=50, null=True)),
                ('title', models.CharField(blank=True, default='heading text', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_image', models.FileField(blank=True, null=True, upload_to='page_images/', verbose_name='primary_image')),
                ('sort_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banners',
            name='primary_image',
            field=models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='primary_image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='primary_image',
            field=models.FileField(blank=True, null=True, upload_to='blogs/', verbose_name='primary_image'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentcategories',
            name='primary_image',
            field=models.FileField(blank=True, null=True, upload_to='treatments/', verbose_name='primary_image'),
        ),
    ]
