# Generated by Django 3.2.9 on 2022-01-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentcategories',
            name='primary_image',
            field=models.FileField(blank=True, null=True, upload_to='treatments_categories/', verbose_name='primary_image'),
        ),
    ]
