# Generated by Django 3.2.9 on 2022-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_treatmentcategories_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
