# Generated by Django 3.2.9 on 2022-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_appointments_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='meeting_time_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
