# Generated by Django 3.2.9 on 2022-01-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_doctorprescriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcategories',
            name='treatment_id',
        ),
        migrations.AddField(
            model_name='treatmentcategories',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.treatments'),
        ),
    ]
