# Generated by Django 3.2.9 on 2022-02-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20220124_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
