# Generated by Django 3.2.9 on 2022-02-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0016_banners_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='doctor_appointment_at',
            new_name='appointment_from',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='doctor_id',
            new_name='clinic_id',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='amount',
            new_name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_for',
            field=models.CharField(choices=[('MySelf', 'MySelf'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Mother', 'Mother'), ('Father', 'Father'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother-in-law', 'Mother-in-law'), ('Father-in-law', 'Father-in-law'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('None', 'None')], default='MySelf', max_length=20),
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_plan', to='hospital.subscriptionplans'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='meeting_time_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='payment_type',
            field=models.CharField(choices=[('On-Clinic', 'On-Clinic'), ('Internet-Banking', 'Internet-Banking'), ('cod', 'COD'), ('flutterwave', 'FLUTTERWAVE'), ('STRIPE', 'STRIPE'), ('other', 'Other')], default='On-Clinic', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='translation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
