# Generated by Django 3.2.9 on 2022-02-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_appointments_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_verification',
            field=models.BooleanField(default=False),
        ),
    ]
